"""Authoritative verification providers."""

from compliance_engine.verification.base import MockGSTProvider, VerificationProvider
from compliance_engine.verification.debarment_adapter import (
    DEBARMENT_CAPABILITY as DEBARMENT_CAPABILITY_ID,
    DEBARMENT_SOURCE as DEBARMENT_SOURCE_ID,
    DebarmentAdapter,
    DebarmentDefaultHttpTransport,
    DebarmentHttpRequest,
    DebarmentHttpResponse,
    DebarmentHttpTransport,
    DebarmentHttpTransportError,
    DebarmentResponseEnvelope,
    DebarmentResponseParser,
    StaticDebarmentHttpTransport,
    StaticDebarmentTransport,
    derive_match_method,
    http_response_to_envelope,
)
from compliance_engine.verification.debarment_config import (
    DEBARMENT_ENV_PRODUCTION,
    DEBARMENT_ENV_UAT,
    from_env as debarment_config_from_env,
)
from compliance_engine.verification.debarment_models import (
    DEBARMENT_CAPABILITY,
    DEBARMENT_MIN_TLS_VERSION,
    DEBARMENT_SOURCE,
    DebarmentClientCredentials,
    DebarmentConfig,
    DebarmentEndpointConfig,
    DebarmentQuery,
    DebarmentRestrictionStatus,
    DebarmentRestrictionType,
    MatchMethod,
    NormalizedDebarmentData,
    SubjectType,
    normalize_identifier,
)
from compliance_engine.verification.gst_config import (
    GST_ENV_PRODUCTION,
    GST_ENV_UAT,
    GstClientCredentials,
    GstConfig,
    GstEndpointConfig,
    GstSigningConfig,
    from_env as gst_config_from_env,
)
from compliance_engine.verification.gst_http_transport import (
    GstHttpClient,
    GstHttpResponse,
    GstHttpTransport,
    GstTransportError,
    StaticGstTransport,
    http_response_to_envelope,
)
from compliance_engine.verification.gstn_adapter import (
    GSTNAdapter,
    GstResponseParser,
    NormalizedGstData,
)
from compliance_engine.verification.gstn_returns_adapter import (
    FILING_STATUS_FILED,
    FILING_STATUS_NOT_FILED,
    GSTNReturnsAdapter,
    GST_FINANCIAL_YEAR_ALL,
    GST_RETURN_TYPE_ALL,
    GstReturnQuery,
    GstReturnResponseParser,
    NormalizedGstReturnFilingData,
)
from compliance_engine.verification.mca_adapter import (
    McaAdapter,
    McaQuery,
    McaResponseEnvelope,
    McaResponseParser,
    NormalizedMcaData,
)
from compliance_engine.verification.pan import MockPANProvider
from compliance_engine.verification.pan_adapter import (
    NormalizedPanData,
    PanAdapter,
    PanQuery,
    PanResponseEnvelope,
    PanResponseParser,
)
from compliance_engine.verification.pan_config import (
    PAN_SERVICE_ID,
    PanAgencyCredentials,
    PanClientCredentials,
    PanConfig,
    PanEndpointConfig,
    PanSigningConfig,
    from_env as pan_config_from_env,
    new_request_id as pan_new_request_id,
)
from compliance_engine.verification.pan_http_transport import (
    PanHttpClient,
    PanHttpResponse,
    PanHttpTransport,
    PanTransportError,
    StaticPanTransport,
)
from compliance_engine.verification.pan_soap import (
    PanSoapParseError,
    PanSoapRequest,
    PanSoapRequestBuilder,
    PanSoapResponseParser,
)
from compliance_engine.verification.transport import (
    GstQuery,
    GstResponseEnvelope,
    InProcessTransport,
    SourceResponseEnvelope,
    StaticTransport,
    TransportError,
    VerificationTransport,
)
from compliance_engine.verification.udyam import MockUdyamProvider
from compliance_engine.verification.udyam_adapter import (
    NormalizedUdyamData,
    UdyamAdapter,
    UdyamQuery,
    UdyamResponseEnvelope,
    UdyamResponseParser,
)
from compliance_engine.models.verification import VerificationStatus

__all__ = [
    "DEBARMENT_CAPABILITY",
    "DEBARMENT_CAPABILITY_ID",
    "DEBARMENT_ENV_PRODUCTION",
    "DEBARMENT_ENV_UAT",
    "DEBARMENT_MIN_TLS_VERSION",
    "DEBARMENT_SOURCE",
    "DEBARMENT_SOURCE_ID",
    "DebarmentAdapter",
    "DebarmentClientCredentials",
    "DebarmentConfig",
    "DebarmentDefaultHttpTransport",
    "DebarmentEndpointConfig",
    "DebarmentHttpRequest",
    "DebarmentHttpResponse",
    "DebarmentHttpTransport",
    "DebarmentHttpTransportError",
    "DebarmentQuery",
    "DebarmentResponseEnvelope",
    "DebarmentResponseParser",
    "DebarmentRestrictionStatus",
    "DebarmentRestrictionType",
    "FILING_STATUS_FILED",
    "FILING_STATUS_NOT_FILED",
    "GSTNAdapter",
    "GSTNReturnsAdapter",
    "GST_ENV_PRODUCTION",
    "GST_ENV_UAT",
    "GST_FINANCIAL_YEAR_ALL",
    "GST_RETURN_TYPE_ALL",
    "GstClientCredentials",
    "GstConfig",
    "GstEndpointConfig",
    "GstHttpClient",
    "GstHttpResponse",
    "GstHttpTransport",
    "GstQuery",
    "GstResponseEnvelope",
    "GstResponseParser",
    "GstReturnQuery",
    "GstReturnResponseParser",
    "GstSigningConfig",
    "GstTransportError",
    "InProcessTransport",
    "MatchMethod",
    "McaAdapter",
    "McaQuery",
    "McaResponseEnvelope",
    "McaResponseParser",
    "MockGSTProvider",
    "MockPANProvider",
    "MockUdyamProvider",
    "NormalizedDebarmentData",
    "NormalizedGstData",
    "NormalizedGstReturnFilingData",
    "NormalizedMcaData",
    "NormalizedPanData",
    "NormalizedUdyamData",
    "PAN_SERVICE_ID",
    "PanAdapter",
    "PanAgencyCredentials",
    "PanClientCredentials",
    "PanConfig",
    "PanEndpointConfig",
    "PanHttpClient",
    "PanHttpResponse",
    "PanHttpTransport",
    "PanQuery",
    "PanResponseEnvelope",
    "PanResponseParser",
    "PanSigningConfig",
    "PanSoapParseError",
    "PanSoapRequest",
    "PanSoapRequestBuilder",
    "PanSoapResponseParser",
    "PanTransportError",
    "SourceResponseEnvelope",
    "StaticDebarmentHttpTransport",
    "StaticDebarmentTransport",
    "StaticGstTransport",
    "StaticPanTransport",
    "StaticTransport",
    "SubjectType",
    "TransportError",
    "UdyamAdapter",
    "UdyamQuery",
    "UdyamResponseEnvelope",
    "UdyamResponseParser",
    "VerificationProvider",
    "VerificationStatus",
    "VerificationTransport",
    "debarment_config_from_env",
    "derive_match_method",
    "gst_config_from_env",
    "http_response_to_envelope",
    "normalize_identifier",
    "pan_config_from_env",
    "pan_new_request_id",
]
