"""Repository protocols (seams) for durable storage.

Every protocol has an in-memory implementation
(:mod:`infrastructure.persistence.memory`) and a PostgreSQL
implementation (:mod:`infrastructure.persistence.postgres`) that honour
the *same* invariants. Domain code depends only on these protocols, never
on SQL or Redis commands.

Conventions:

* ``add`` inserts; duplicates raise :class:`DuplicateRecordError`.
* ``save`` upserts idempotently on the declared unique key.
* missing-foreign-key writes raise :class:`MissingReferenceError`.
* audit events and the outbox are append-only (``add``).
"""

from __future__ import annotations

from typing import Protocol

from infrastructure.persistence.records import (
    AuditEventRecord,
    BidderRecord,
    ComplianceResultRecord,
    DocumentRecord,
    EvidenceRecord,
    ExplanationRecord,
    FindingRecord,
    FlagSnapshotRecord,
    FlagStateRecord,
    OutboxEventRecord,
    ProcessingJobRecord,
    SubmissionRecord,
    VerificationRecord,
)


class BidderRepository(Protocol):
    def add(self, record: BidderRecord) -> BidderRecord: ...
    def get(self, bidder_id: str) -> BidderRecord | None: ...


class SubmissionRepository(Protocol):
    def add(self, record: SubmissionRecord) -> SubmissionRecord: ...
    def get(self, submission_id: str) -> SubmissionRecord | None: ...
    def save(self, record: SubmissionRecord) -> SubmissionRecord: ...
    def list_by_bidder(self, bidder_id: str) -> list[SubmissionRecord]: ...


class DocumentRepository(Protocol):
    def add(self, record: DocumentRecord) -> DocumentRecord: ...
    def get(self, document_id: str) -> DocumentRecord | None: ...
    def list_by_submission(self, submission_id: str) -> list[DocumentRecord]: ...
    def list_by_bidder(self, bidder_id: str) -> list[DocumentRecord]: ...


class EvidenceRepository(Protocol):
    def add(self, record: EvidenceRecord) -> EvidenceRecord: ...
    def get(self, evidence_id: str) -> EvidenceRecord | None: ...
    def list_by_bidder(self, bidder_id: str) -> list[EvidenceRecord]: ...
    def list_by_document(self, document_id: str) -> list[EvidenceRecord]: ...


class VerificationRepository(Protocol):
    def save(self, record: VerificationRecord) -> VerificationRecord: ...
    def get(self, verification_id: str) -> VerificationRecord | None: ...
    def list_by_bidder(self, bidder_id: str) -> list[VerificationRecord]: ...


class ComplianceResultRepository(Protocol):
    def save(self, record: ComplianceResultRecord) -> ComplianceResultRecord: ...
    def get(self, bidder_id: str, requirement_id: str) -> ComplianceResultRecord | None: ...
    def list_by_bidder(self, bidder_id: str) -> list[ComplianceResultRecord]: ...


class FindingRepository(Protocol):
    def save(self, record: FindingRecord) -> FindingRecord: ...
    def get(self, finding_id: str) -> FindingRecord | None: ...
    def list_by_bidder(self, bidder_id: str) -> list[FindingRecord]: ...
    def list_by_flag(self, bidder_id: str, flag_id: str) -> list[FindingRecord]: ...


class ExplanationRepository(Protocol):
    def save(self, record: ExplanationRecord) -> ExplanationRecord: ...
    def get(self, explanation_id: str) -> ExplanationRecord | None: ...
    def list_by_flag(self, bidder_id: str, flag_id: str) -> list[ExplanationRecord]: ...
    def list_by_bidder(self, bidder_id: str) -> list[ExplanationRecord]: ...


class JobRepository(Protocol):
    def save(self, record: ProcessingJobRecord) -> ProcessingJobRecord: ...
    def get(self, job_id: str) -> ProcessingJobRecord | None: ...
    def find_by_idempotency_key(self, key: str) -> ProcessingJobRecord | None: ...
    def list_by_submission(self, submission_id: str) -> list[ProcessingJobRecord]: ...


class AuditRepository(Protocol):
    def add(self, record: AuditEventRecord) -> AuditEventRecord: ...
    def list_for(self, aggregate_type: str, aggregate_id: str) -> list[AuditEventRecord]: ...
    def list_by_correlation(self, correlation_id: str) -> list[AuditEventRecord]: ...


class OutboxRepository(Protocol):
    def add(self, record: OutboxEventRecord) -> OutboxEventRecord: ...
    def list_unpublished(self, limit: int = 100) -> list[OutboxEventRecord]: ...
    def record_attempt(self, event_id: str) -> None: ...
    def mark_published(self, event_id: str, published_at: float) -> bool: ...


class FlagRepository(Protocol):
    def save_state(self, record: FlagStateRecord) -> FlagStateRecord: ...
    def get_state(self, bidder_id: str, flag_id: str) -> FlagStateRecord | None: ...
    def list_states(self, bidder_id: str) -> list[FlagStateRecord]: ...
    def save_snapshot(self, record: FlagSnapshotRecord) -> FlagSnapshotRecord: ...
    def get_snapshot(self, snapshot_id: str) -> FlagSnapshotRecord | None: ...
    def list_snapshots(self, bidder_id: str) -> list[FlagSnapshotRecord]: ...


__all__ = [
    "AuditRepository",
    "BidderRepository",
    "ComplianceResultRepository",
    "DocumentRepository",
    "EvidenceRepository",
    "ExplanationRepository",
    "FindingRepository",
    "FlagRepository",
    "JobRepository",
    "OutboxRepository",
    "SubmissionRepository",
    "VerificationRepository",
]