"""Canonical verification flag definitions.

The registry stores static flag metadata. Instance-specific explanations
belong on ``ComplianceResult.reason`` and related fields, not here.
"""

from enum import StrEnum

from pydantic import BaseModel


class FlagSeverity(StrEnum):
    """Relative seriousness of a verification flag."""

    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FlagDefinition(BaseModel):
    """Static definition of a machine-readable verification flag."""

    flag_id: str
    severity: FlagSeverity
    capability: str
    title: str
    description: str


class UnknownFlagError(KeyError):
    """Raised when a flag ID is not present in the registry."""


def _flag(
    flag_id: str,
    severity: FlagSeverity,
    capability: str,
    title: str,
    description: str,
) -> FlagDefinition:
    return FlagDefinition(
        flag_id=flag_id,
        severity=severity,
        capability=capability,
        title=title,
        description=description,
    )


# Reference constant for the GSTIN missing flag
GSTIN_MISSING = "GSTIN_MISSING"


_FLAGS: tuple[FlagDefinition, ...] = (
    _flag(
        "ADDRESS_MISMATCH",
        FlagSeverity.MEDIUM,
        "Bidder Identity",
        "Address mismatch",
        "Address mismatch",
    ),
    _flag(
        "ADDRESS_SHARING_SUSPICIOUS",
        FlagSeverity.MEDIUM,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Address sharing suspicious",
        "Address sharing suspicious",
    ),
    _flag(
        "AGGREGATED_REGISTRATION_STATUS_INVALID",
        FlagSeverity.HIGH,
        "Registration / Status Checks",
        "Aggregated registration status invalid",
        "Aggregated registration status invalid",
    ),
    _flag(
        "ALTERNATIVE_EVIDENCE_INSUFFICIENT",
        FlagSeverity.HIGH,
        "Missing / Completeness Checks",
        "Alternative evidence insufficient",
        "Alternative evidence insufficient",
    ),
    _flag(
        "AUDITABILITY_VERIFICATION_INCOMPLETE",
        FlagSeverity.LOW,
        "Auditability / Evidence Traceability",
        "Auditability verification incomplete",
        "Auditability verification incomplete",
    ),
    _flag(
        "AUDITED_STATUS_MISSING",
        FlagSeverity.MEDIUM,
        "Financial Capacity",
        "Audited status missing",
        "Audited status missing",
    ),
    _flag(
        "AUDIT_TRAIL_INCOMPLETE",
        FlagSeverity.MEDIUM,
        "Auditability / Evidence Traceability",
        "Audit trail incomplete",
        "Audit trail incomplete",
    ),
    _flag(
        "AUTHORIZATION_TERRITORY_MISMATCH",
        FlagSeverity.MEDIUM,
        "OEM Authorization",
        "Authorization territory mismatch",
        "Authorization territory mismatch",
    ),
    _flag(
        "AUTHORIZATION_TYPE_MISMATCH",
        FlagSeverity.MEDIUM,
        "OEM Authorization",
        "Authorization type mismatch",
        "Authorization type mismatch",
    ),
    _flag(
        "AUTHORIZED_PRODUCT_RANGE_INSUFFICIENT",
        FlagSeverity.HIGH,
        "OEM Authorization",
        "Authorized product range insufficient",
        "Authorized product range insufficient",
    ),
    _flag(
        "BIDDER_BLACKLISTED",
        FlagSeverity.CRITICAL,
        "Blacklisting / Debarment",
        "Bidder blacklisted",
        "Bidder blacklisted",
    ),
    _flag(
        "BIDDER_DEBARRED",
        FlagSeverity.CRITICAL,
        "Blacklisting / Debarment",
        "Bidder debarred",
        "Bidder debarred",
    ),
    _flag(
        "BIDDER_NAME_MISMATCH",
        FlagSeverity.HIGH,
        "Bidder Identity",
        "Bidder name mismatch",
        "Bidder name mismatch",
    ),
    _flag(
        "BIDDER_SUSPENDED",
        FlagSeverity.CRITICAL,
        "Blacklisting / Debarment",
        "Bidder suspended",
        "Bidder suspended",
    ),
    _flag(
        "BIDDER_UNDER_INVESTIGATION",
        FlagSeverity.HIGH,
        "Blacklisting / Debarment",
        "Bidder under investigation",
        "Bidder under investigation",
    ),
    _flag(
        "BID_ASSESSMENT_INCOMPLETE",
        FlagSeverity.LOW,
        "Overall Bid-Level Assessment",
        "Bid assessment incomplete",
        "Bid assessment incomplete",
    ),
    _flag(
        "BID_LEVEL_COMPLIANT",
        FlagSeverity.INFO,
        "Overall Bid-Level Assessment",
        "Bid level compliant",
        "Bid level compliant",
    ),
    _flag(
        "BID_LEVEL_MISSING_EVIDENCE",
        FlagSeverity.HIGH,
        "Overall Bid-Level Assessment",
        "Bid level missing evidence",
        "Bid level missing evidence",
    ),
    _flag(
        "BID_LEVEL_NON_COMPLIANT",
        FlagSeverity.CRITICAL,
        "Overall Bid-Level Assessment",
        "Bid level non-compliant",
        "Bid level non-compliant",
    ),
    _flag(
        "BID_LEVEL_PARTIAL_COMPLIANCE",
        FlagSeverity.MEDIUM,
        "Overall Bid-Level Assessment",
        "Bid level partial compliance",
        "Bid level partial compliance",
    ),
    _flag(
        "BID_LEVEL_UNVERIFIABLE",
        FlagSeverity.MEDIUM,
        "Overall Bid-Level Assessment",
        "Bid level unverifiable",
        "Bid level unverifiable",
    ),
    _flag(
        "BIS_CERTIFICATE_EXPIRED",
        FlagSeverity.HIGH,
        "BIS / Product Certification",
        "BIS certificate expired",
        "BIS certificate expired",
    ),
    _flag(
        "BIS_CERTIFICATE_INVALID",
        FlagSeverity.HIGH,
        "BIS / Product Certification",
        "BIS certificate invalid",
        "BIS certificate invalid",
    ),
    _flag(
        "BIS_CERTIFICATE_NOT_FOUND",
        FlagSeverity.HIGH,
        "BIS / Product Certification",
        "BIS certificate not found",
        "BIS certificate not found",
    ),
    _flag(
        "BIS_CERTIFICATE_SUSPENDED_REVOKED",
        FlagSeverity.CRITICAL,
        "BIS / Product Certification",
        "BIS certificate suspended or revoked",
        "BIS certificate suspended or revoked",
    ),
    _flag(
        "BIS_FACILITY_LOCATION_INELIGIBLE",
        FlagSeverity.HIGH,
        "BIS / Product Certification",
        "BIS facility location ineligible",
        "BIS facility location ineligible",
    ),
    _flag(
        "BIS_PRODUCT_SCOPE_MISMATCH",
        FlagSeverity.HIGH,
        "BIS / Product Certification",
        "BIS product scope mismatch",
        "BIS product scope mismatch",
    ),
    _flag(
        "BIS_QUALITY_GRADE_BELOW_REQUIREMENT",
        FlagSeverity.HIGH,
        "BIS / Product Certification",
        "BIS quality grade below requirement",
        "BIS quality grade below requirement",
    ),
    _flag(
        "BIS_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "BIS / Product Certification",
        "BIS verification unavailable",
        "BIS verification unavailable",
    ),
    _flag(
        "BLACKLIST_STATUS_UNKNOWN",
        FlagSeverity.MEDIUM,
        "Blacklisting / Debarment",
        "Blacklist status unknown",
        "Blacklist status unknown",
    ),
    _flag(
        "BUSINESS_TYPE_INELIGIBLE",
        FlagSeverity.HIGH,
        "MCA21",
        "Business type ineligible",
        "Business type ineligible",
    ),
    _flag(
        "CAPABILITY_NOT_APPLICABLE_UNCLEAR",
        FlagSeverity.MEDIUM,
        "Missing / Completeness Checks",
        "Capability applicability unclear",
        "Capability applicability unclear",
    ),
    _flag(
        "CA_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "CA / UDIN",
        "CA identity mismatch",
        "CA identity mismatch",
    ),
    _flag(
        "CA_NOT_REGISTERED",
        FlagSeverity.HIGH,
        "CA / UDIN",
        "CA not registered",
        "CA not registered",
    ),
    _flag(
        "CA_PROFESSIONAL_STATUS_INVALID",
        FlagSeverity.HIGH,
        "CA / UDIN",
        "CA professional status invalid",
        "CA professional status invalid",
    ),
    _flag(
        "CA_UDIN_EXPIRED",
        FlagSeverity.HIGH,
        "CA / UDIN",
        "CA UDIN expired",
        "CA UDIN expired",
    ),
    _flag(
        "CA_UDIN_INVALID",
        FlagSeverity.HIGH,
        "CA / UDIN",
        "CA UDIN invalid",
        "CA UDIN invalid",
    ),
    _flag(
        "CA_UDIN_NOT_FOUND",
        FlagSeverity.HIGH,
        "CA / UDIN",
        "CA UDIN not found",
        "CA UDIN not found",
    ),
    _flag(
        "CA_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "CA / UDIN",
        "CA verification unavailable",
        "CA verification unavailable",
    ),
    _flag(
        "CERTIFICATE_TYPE_MISMATCH",
        FlagSeverity.MEDIUM,
        "CA / UDIN",
        "Certificate type mismatch",
        "Certificate type mismatch",
    ),
    _flag(
        "CERTIFICATE_VALIDITY_EXPIRED",
        FlagSeverity.HIGH,
        "CA / UDIN",
        "Certificate validity expired",
        "Certificate validity expired",
    ),
    _flag(
        "CIN_INVALID",
        FlagSeverity.HIGH,
        "MCA21",
        "CIN invalid",
        "CIN invalid",
    ),
    _flag(
        "CIN_NOT_FOUND",
        FlagSeverity.HIGH,
        "MCA21",
        "CIN not found",
        "CIN not found",
    ),
    _flag(
        "COMPANY_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "MCA21",
        "Company identity mismatch",
        "Company identity mismatch",
    ),
    _flag(
        "COMPANY_INACTIVE",
        FlagSeverity.HIGH,
        "MCA21",
        "Company inactive",
        "Company inactive",
    ),
    _flag(
        "COMPANY_STRIKE_OFF",
        FlagSeverity.CRITICAL,
        "MCA21",
        "Company struck off",
        "Company struck off",
    ),
    _flag(
        "COMPANY_UNDER_LIQUIDATION",
        FlagSeverity.CRITICAL,
        "MCA21",
        "Company under liquidation",
        "Company under liquidation",
    ),
    _flag(
        "COMPLETENESS_VERIFICATION_INCOMPLETE",
        FlagSeverity.LOW,
        "Missing / Completeness Checks",
        "Completeness verification incomplete",
        "Completeness verification incomplete",
    ),
    _flag(
        "COMPLIANCE_SCORE_LOW",
        FlagSeverity.MEDIUM,
        "Compliance Score / Risk Level",
        "Compliance score low",
        "Compliance score low",
    ),
    _flag(
        "CONDITIONAL_APPLICABILITY_UNCLEAR",
        FlagSeverity.MEDIUM,
        "Tender Applicability / Exemption Checks",
        "Conditional applicability unclear",
        "Conditional applicability unclear",
    ),
    _flag(
        "CONDITIONAL_FIELD_MISSING",
        FlagSeverity.MEDIUM,
        "Missing / Completeness Checks",
        "Conditional field missing",
        "Conditional field missing",
    ),
    _flag(
        "CONFLICTING_EXEMPTIONS",
        FlagSeverity.HIGH,
        "Tender Applicability / Exemption Checks",
        "Conflicting exemptions",
        "Conflicting exemptions",
    ),
    _flag(
        "COVERED_EMPLOYEE_COUNT_BELOW_THRESHOLD",
        FlagSeverity.HIGH,
        "ESIC",
        "Covered employee count below threshold",
        "Covered employee count below threshold",
    ),
    _flag(
        "CROSS_SOURCE_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "Bidder Identity",
        "Cross-source identity mismatch",
        (
            "Verified identity-bearing names from two or more authoritative "
            "sources (e.g. GST, PAN, Udyam, MCA) materially differ after "
            "deterministic normalization. Indicates a bidder identity "
            "consistency concern; downstream policy decides compliance."
        ),
    ),
    _flag(
        "CRITICAL_CAPABILITY_FAILED",
        FlagSeverity.CRITICAL,
        "Overall Bid-Level Assessment",
        "Critical capability failed",
        "Critical capability failed",
    ),
    _flag(
        "CRITICAL_SOURCE_UNAVAILABLE",
        FlagSeverity.HIGH,
        "Verification Infrastructure Checks",
        "Critical source unavailable",
        "Critical source unavailable",
    ),
    _flag(
        "CROSS_BIDDER_VERIFICATION_INCOMPLETE",
        FlagSeverity.LOW,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Cross-bidder verification incomplete",
        "Cross-bidder verification incomplete",
    ),
    _flag(
        "CROSS_BIDDER_DOCUMENT_NEAR_DUPLICATE",
        FlagSeverity.MEDIUM,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Cross-bidder document near-duplicate",
        "Near-identical document content detected across different bidders.",
    ),
    _flag(
        "CROSS_BIDDER_DOCUMENT_REUSED",
        FlagSeverity.HIGH,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Cross-bidder document reused",
        "Identical document content or artifact detected across different bidders.",
    ),
    _flag(
        "CROSS_DOCUMENT_ADDRESS_CONFLICT",
        FlagSeverity.HIGH,
        "Cross-Document Verification",
        "Cross-document address conflict",
        "Cross-document address conflict",
    ),
    _flag(
        "CROSS_DOCUMENT_DATE_SEQUENCE_INVALID",
        FlagSeverity.HIGH,
        "Cross-Document Verification",
        "Cross-document date sequence invalid",
        "Cross-document date sequence invalid",
    ),
    _flag(
        "CROSS_DOCUMENT_ENTITY_TYPE_CONFLICT",
        FlagSeverity.HIGH,
        "Cross-Document Verification",
        "Cross-document entity type conflict",
        "Cross-document entity type conflict",
    ),
    _flag(
        "CROSS_DOCUMENT_FINANCIAL_YEAR_MISMATCH",
        FlagSeverity.MEDIUM,
        "Cross-Document Verification",
        "Cross-document financial year mismatch",
        "Cross-document financial year mismatch",
    ),
    _flag(
        "CROSS_DOCUMENT_IDENTIFIER_CONFLICT",
        FlagSeverity.CRITICAL,
        "Cross-Document Verification",
        "Cross-document identifier conflict",
        "Cross-document identifier conflict",
    ),
    _flag(
        "CROSS_DOCUMENT_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "Bidder Identity",
        "Cross-document identity mismatch",
        "Cross-document identity mismatch",
    ),
    _flag(
        "CROSS_DOCUMENT_NAME_CONFLICT",
        FlagSeverity.HIGH,
        "Cross-Document Verification",
        "Cross-document name conflict",
        "Cross-document name conflict",
    ),
    _flag(
        "CROSS_DOCUMENT_PRODUCT_MISMATCH",
        FlagSeverity.MEDIUM,
        "Cross-Document Verification",
        "Cross-document product mismatch",
        "Cross-document product mismatch",
    ),
    _flag(
        "CROSS_DOCUMENT_MANUFACTURER_MISMATCH",
        FlagSeverity.MEDIUM,
        "Cross-Document Verification",
        "Cross-document manufacturer mismatch",
        "Cross-document manufacturer mismatch",
    ),
    _flag(
        "CROSS_DOCUMENT_TEMPORAL_GAP",
        FlagSeverity.MEDIUM,
        "Cross-Document Verification",
        "Cross-document temporal gap",
        "Cross-document temporal gap",
    ),
    _flag(
        "CROSS_DOCUMENT_VERIFICATION_INCOMPLETE",
        FlagSeverity.LOW,
        "Cross-Document Verification",
        "Cross-document verification incomplete",
        "Cross-document verification incomplete",
    ),
    _flag(
        "DEBARMENT_CLEARANCE_INVALID",
        FlagSeverity.HIGH,
        "Blacklisting / Debarment",
        "Debarment clearance invalid",
        "Debarment clearance invalid",
    ),
    _flag(
        "DEBARMENT_CLEARANCE_MISSING",
        FlagSeverity.HIGH,
        "Blacklisting / Debarment",
        "Debarment clearance missing",
        "Debarment clearance missing",
    ),
    _flag(
        "DEBARMENT_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Blacklisting / Debarment",
        "Debarment verification unavailable",
        "Debarment verification unavailable",
    ),
    _flag(
        "DIGILOCKER_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "DigiLocker / Document Verification",
        "DigiLocker verification unavailable",
        "DigiLocker verification unavailable",
    ),
    _flag(
        "DIGITAL_DOCUMENT_EXPIRED",
        FlagSeverity.HIGH,
        "DigiLocker / Document Verification",
        "Digital document expired",
        "Digital document expired",
    ),
    _flag(
        "DIGITAL_DOCUMENT_HASH_MISMATCH",
        FlagSeverity.HIGH,
        "DigiLocker / Document Verification",
        "Digital document hash mismatch",
        "Digital document hash mismatch",
    ),
    _flag(
        "DIGITAL_DOCUMENT_NOT_FOUND",
        FlagSeverity.HIGH,
        "DigiLocker / Document Verification",
        "Digital document not found",
        "Digital document not found",
    ),
    _flag(
        "DIGITAL_DOCUMENT_REVOKED",
        FlagSeverity.CRITICAL,
        "DigiLocker / Document Verification",
        "Digital document revoked",
        "Digital document revoked",
    ),
    _flag(
        "DIGITAL_DOCUMENT_SIGNATURE_INVALID",
        FlagSeverity.HIGH,
        "DigiLocker / Document Verification",
        "Digital document signature invalid",
        "Digital document signature invalid",
    ),
    _flag(
        "DIGITAL_SIGNATURE_VERIFICATION_FAILED",
        FlagSeverity.HIGH,
        "DigiLocker / Document Verification",
        "Digital signature verification failed",
        "Digital signature verification failed",
    ),
    _flag(
        "DIRECTOR_SHARING_SUSPICIOUS",
        FlagSeverity.HIGH,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Director sharing suspicious",
        "Director sharing suspicious",
    ),
    _flag(
        "DOCUMENT_TYPE_CONFIDENCE_LOW",
        FlagSeverity.LOW,
        "Evidence Quality Checks",
        "Document type confidence low",
        "Document type confidence low",
    ),
    _flag(
        "EMPLOYEE_COUNT_BELOW_THRESHOLD",
        FlagSeverity.HIGH,
        "EPFO",
        "Employee count below threshold",
        "Employee count below threshold",
    ),
    _flag(
        "ENTITY_TYPE_MISMATCH",
        FlagSeverity.HIGH,
        "Bidder Identity",
        "Entity type mismatch",
        "Entity type mismatch",
    ),
    _flag(
        "EPFO_CONTRIBUTION_DEFAULT",
        FlagSeverity.HIGH,
        "EPFO",
        "EPFO contribution in default",
        "EPFO contribution in default",
    ),
    _flag(
        "EPFO_OUTSTANDING_LIABILITY_EXCESSIVE",
        FlagSeverity.MEDIUM,
        "EPFO",
        "EPFO outstanding liability excessive",
        "EPFO outstanding liability excessive",
    ),
    _flag(
        "EPFO_REGISTRATION_INACTIVE",
        FlagSeverity.HIGH,
        "EPFO",
        "EPFO registration inactive",
        "EPFO registration inactive",
    ),
    _flag(
        "EPFO_REGISTRATION_INVALID",
        FlagSeverity.HIGH,
        "EPFO",
        "EPFO registration invalid",
        "EPFO registration invalid",
    ),
    _flag(
        "EPFO_REGISTRATION_NOT_FOUND",
        FlagSeverity.HIGH,
        "EPFO",
        "EPFO registration not found",
        "EPFO registration not found",
    ),
    _flag(
        "EPFO_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "EPFO",
        "EPFO verification unavailable",
        "EPFO verification unavailable",
    ),
    _flag(
        "ESIC_CONTRIBUTION_DEFAULT",
        FlagSeverity.HIGH,
        "ESIC",
        "ESIC contribution in default",
        "ESIC contribution in default",
    ),
    _flag(
        "ESIC_REGISTRATION_INACTIVE",
        FlagSeverity.HIGH,
        "ESIC",
        "ESIC registration inactive",
        "ESIC registration inactive",
    ),
    _flag(
        "ESIC_REGISTRATION_INVALID",
        FlagSeverity.HIGH,
        "ESIC",
        "ESIC registration invalid",
        "ESIC registration invalid",
    ),
    _flag(
        "ESIC_REGISTRATION_NOT_FOUND",
        FlagSeverity.HIGH,
        "ESIC",
        "ESIC registration not found",
        "ESIC registration not found",
    ),
    _flag(
        "ESIC_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "ESIC",
        "ESIC verification unavailable",
        "ESIC verification unavailable",
    ),
    _flag(
        "EVIDENCE_AGE_EXCESSIVE",
        FlagSeverity.MEDIUM,
        "Evidence Quality Checks",
        "Evidence age excessive",
        "Evidence age excessive",
    ),
    _flag(
        "EVIDENCE_CHAIN_INCOMPLETE",
        FlagSeverity.MEDIUM,
        "Auditability / Evidence Traceability",
        "Evidence chain incomplete",
        "Evidence chain incomplete",
    ),
    _flag(
        "EVIDENCE_CONFIDENCE_BELOW_THRESHOLD",
        FlagSeverity.MEDIUM,
        "Evidence Quality Checks",
        "Evidence confidence below threshold",
        "Evidence confidence below threshold",
    ),
    _flag(
        "EVIDENCE_GROUNDING_INSUFFICIENT",
        FlagSeverity.MEDIUM,
        "Missing / Completeness Checks",
        "Evidence grounding insufficient",
        "Evidence grounding insufficient",
    ),
    _flag(
        "EVIDENCE_GROUNDING_UNRELIABLE",
        FlagSeverity.MEDIUM,
        "Evidence Quality Checks",
        "Evidence grounding unreliable",
        "Evidence grounding unreliable",
    ),
    _flag(
        "EVIDENCE_LINKAGE_BROKEN",
        FlagSeverity.HIGH,
        "Auditability / Evidence Traceability",
        "Evidence linkage broken",
        "Evidence linkage broken",
    ),
    _flag(
        "EVIDENCE_PROVENANCE_UNCLEAR",
        FlagSeverity.MEDIUM,
        "Evidence Quality Checks",
        "Evidence provenance unclear",
        "Evidence provenance unclear",
    ),
    _flag(
        "EVIDENCE_QUALITY_VERIFICATION_INCOMPLETE",
        FlagSeverity.LOW,
        "Evidence Quality Checks",
        "Evidence quality verification incomplete",
        "Evidence quality verification incomplete",
    ),
    _flag(
        "EXACT_DUPLICATE_BIDDER_DETECTED",
        FlagSeverity.CRITICAL,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Exact duplicate bidder detected",
        "Exact duplicate bidder detected",
    ),
    _flag(
        "EXEMPTION_CONDITION_NOT_MET",
        FlagSeverity.HIGH,
        "Tender Applicability / Exemption Checks",
        "Exemption condition not met",
        "Exemption condition not met",
    ),
    _flag(
        "EXEMPTION_EVIDENCE_INSUFFICIENT",
        FlagSeverity.HIGH,
        "Tender Applicability / Exemption Checks",
        "Exemption evidence insufficient",
        "Exemption evidence insufficient",
    ),
    _flag(
        "EXEMPTION_NOT_RECOGNIZED_FOR_TENDER",
        FlagSeverity.HIGH,
        "Tender Applicability / Exemption Checks",
        "Exemption not recognized for tender",
        "Exemption not recognized for tender",
    ),
    _flag(
        "FALLBACK_VERIFICATION_INCOMPLETE",
        FlagSeverity.MEDIUM,
        "Verification Infrastructure Checks",
        "Fallback verification incomplete",
        "Fallback verification incomplete",
    ),
    _flag(
        "FINANCIAL_CAPACITY_MISSING",
        FlagSeverity.HIGH,
        "Financial Capacity",
        "Financial capacity evidence missing",
        "Financial capacity evidence missing",
    ),
    _flag(
        "FINANCIAL_DATA_INCONSISTENCY",
        FlagSeverity.HIGH,
        "Financial Capacity",
        "Financial data inconsistency",
        "Financial data inconsistency",
    ),
    _flag(
        "FINANCIAL_PROFILE_ANOMALY",
        FlagSeverity.MEDIUM,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Financial profile anomaly",
        "Financial profile anomaly",
    ),
    _flag(
        "FINANCIAL_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Financial Capacity",
        "Financial verification unavailable",
        "Financial verification unavailable",
    ),
    _flag(
        "FINANCIAL_YEAR_MISSING",
        FlagSeverity.HIGH,
        "Financial Capacity",
        "Financial year missing",
        "Financial year missing",
    ),
    _flag(
        "GROUNDING_INSUFFICIENT",
        FlagSeverity.MEDIUM,
        "Evidence Quality Checks",
        "Grounding insufficient",
        "Grounding insufficient",
    ),
    _flag(
        "GSTIN_INVALID",
        FlagSeverity.HIGH,
        "GST / GSTN",
        "GSTIN invalid",
        "GSTIN invalid",
    ),
    _flag(
        "GSTIN_MISSING",
        FlagSeverity.HIGH,
        "GST / GSTN",
        "GSTIN missing",
        "GSTIN missing",
    ),
    _flag(
        "GSTIN_NOT_FOUND",
        FlagSeverity.HIGH,
        "GST / GSTN",
        "GSTIN not found",
        "GSTIN not found",
    ),
    _flag(
        "GST_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "GST / GSTN",
        "GST identity mismatch",
        "GST identity mismatch",
    ),
    _flag(
        "GST_INACTIVE",
        FlagSeverity.HIGH,
        "GST / GSTN",
        "GST registration inactive",
        "GST registration inactive",
    ),
    _flag(
        "GST_RETURN_COMPLIANCE_ISSUE",
        FlagSeverity.HIGH,
        "GST / GSTN",
        "GST return compliance issue",
        "GST return compliance issue",
    ),
    _flag(
        "GST_RETURN_EVIDENCE_MISSING",
        FlagSeverity.HIGH,
        "GST / GSTN",
        "GST return evidence missing",
        "GST return evidence missing",
    ),
    _flag(
        "GST_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "GST / GSTN",
        "GST verification unavailable",
        "GST verification unavailable",
    ),
    _flag(
        "IDENTIFIER_ENTITY_MISMATCH",
        FlagSeverity.CRITICAL,
        "Bidder Identity",
        "Identifier belongs to another entity",
        "Identifier belongs to another entity",
    ),
    _flag(
        "INCORPORATION_DATE_NON_COMPLIANT",
        FlagSeverity.HIGH,
        "MCA21",
        "Incorporation date non-compliant",
        "Incorporation date non-compliant",
    ),
    _flag(
        "INFRASTRUCTURE_VERIFICATION_INCOMPLETE",
        FlagSeverity.LOW,
        "Verification Infrastructure Checks",
        "Infrastructure verification incomplete",
        "Infrastructure verification incomplete",
    ),
    _flag(
        "INTEGRITY_UNDERTAKING_MISSING",
        FlagSeverity.HIGH,
        "Blacklisting / Debarment",
        "Integrity undertaking missing",
        "Integrity undertaking missing",
    ),
    _flag(
        "ISSUING_AUTHORITY_INVALID",
        FlagSeverity.HIGH,
        "DigiLocker / Document Verification",
        "Issuing authority invalid",
        "Issuing authority invalid",
    ),
    _flag(
        "ISSUING_AUTHORITY_NOT_RECOGNIZED",
        FlagSeverity.HIGH,
        "Other Applicable Statutory Requirements",
        "Issuing authority not recognized",
        "Issuing authority not recognized",
    ),
    _flag(
        "ITR_DATA_INCONSISTENCY",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "ITR data inconsistency",
        "ITR data inconsistency",
    ),
    _flag(
        "ITR_MISSING",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "ITR missing",
        "ITR missing",
    ),
    _flag(
        "ITR_NOT_FILED",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "ITR not filed",
        "ITR not filed",
    ),
    _flag(
        "ITR_OUTDATED",
        FlagSeverity.MEDIUM,
        "PAN / Income Tax",
        "ITR outdated",
        "ITR outdated",
    ),
    _flag(
        "LOCAL_CONTENT_BELOW_THRESHOLD",
        FlagSeverity.HIGH,
        "Make in India / Local Content",
        "Local content below threshold",
        "Local content below threshold",
    ),
    _flag(
        "LOCAL_CONTENT_CLAIM_INCONSISTENT",
        FlagSeverity.HIGH,
        "Make in India / Local Content",
        "Local content claim inconsistent",
        "Local content claim inconsistent",
    ),
    _flag(
        "LOCAL_CONTENT_EVIDENCE_MISSING",
        FlagSeverity.HIGH,
        "Make in India / Local Content",
        "Local content evidence missing",
        "Local content evidence missing",
    ),
    _flag(
        "LOCAL_CONTENT_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Make in India / Local Content",
        "Local content verification unavailable",
        "Local content verification unavailable",
    ),
    _flag(
        "MAKE_IN_INDIA_EXEMPTION_INVALID",
        FlagSeverity.HIGH,
        "Make in India / Local Content",
        "Make in India exemption invalid",
        "Make in India exemption invalid",
    ),
    _flag(
        "MANDATORY_CAPABILITY_MISSING",
        FlagSeverity.HIGH,
        "Tender Applicability / Exemption Checks",
        "Mandatory capability missing",
        "Mandatory capability missing",
    ),
    _flag(
        "MANUFACTURING_LOCATION_INELIGIBLE",
        FlagSeverity.HIGH,
        "Make in India / Local Content",
        "Manufacturing location ineligible",
        "Manufacturing location ineligible",
    ),
    _flag(
        "MCA_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "MCA21",
        "MCA verification unavailable",
        "MCA verification unavailable",
    ),
    _flag(
        "MISSING_REASON_NOT_SPECIFIED",
        FlagSeverity.LOW,
        "Missing / Completeness Checks",
        "Missing reason not specified",
        "Missing reason not specified",
    ),
    _flag(
        "MULTIPLE_INACTIVE_REGISTRATIONS",
        FlagSeverity.HIGH,
        "Registration / Status Checks",
        "Multiple inactive registrations",
        "Multiple inactive registrations",
    ),
    _flag(
        "NEAR_DUPLICATE_BIDDER_DETECTED",
        FlagSeverity.HIGH,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Near-duplicate bidder detected",
        "Near-duplicate bidder detected",
    ),
    _flag(
        "NET_WORTH_BELOW_THRESHOLD",
        FlagSeverity.HIGH,
        "Financial Capacity",
        "Net worth below threshold",
        "Net worth below threshold",
    ),
    _flag(
        "NSIC_ENTITY_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "NSIC",
        "NSIC entity identity mismatch",
        "NSIC entity identity mismatch",
    ),
    _flag(
        "NSIC_REGISTRATION_EXPIRED",
        FlagSeverity.HIGH,
        "NSIC",
        "NSIC registration expired",
        "NSIC registration expired",
    ),
    _flag(
        "NSIC_REGISTRATION_INVALID",
        FlagSeverity.HIGH,
        "NSIC",
        "NSIC registration invalid",
        "NSIC registration invalid",
    ),
    _flag(
        "NSIC_REGISTRATION_NOT_FOUND",
        FlagSeverity.HIGH,
        "NSIC",
        "NSIC registration not found",
        "NSIC registration not found",
    ),
    _flag(
        "NSIC_REGISTRATION_TYPE_MISMATCH",
        FlagSeverity.MEDIUM,
        "NSIC",
        "NSIC registration type mismatch",
        "NSIC registration type mismatch",
    ),
    _flag(
        "NSIC_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "NSIC",
        "NSIC verification unavailable",
        "NSIC verification unavailable",
    ),
    _flag(
        "OCR_CONFIDENCE_BELOW_THRESHOLD",
        FlagSeverity.MEDIUM,
        "Evidence Quality Checks",
        "OCR confidence below threshold",
        "OCR confidence below threshold",
    ),
    _flag(
        "OEM_AUTHORIZATION_EXPIRED",
        FlagSeverity.HIGH,
        "OEM Authorization",
        "OEM authorization expired",
        "OEM authorization expired",
    ),
    _flag(
        "OEM_AUTHORIZATION_INVALID",
        FlagSeverity.HIGH,
        "OEM Authorization",
        "OEM authorization invalid",
        "OEM authorization invalid",
    ),
    _flag(
        "OEM_AUTHORIZATION_NOT_PROVIDED",
        FlagSeverity.HIGH,
        "OEM Authorization",
        "OEM authorization not provided",
        "OEM authorization not provided",
    ),
    _flag(
        "OEM_NAME_MISMATCH",
        FlagSeverity.HIGH,
        "OEM Authorization",
        "OEM name mismatch",
        "OEM name mismatch",
    ),
    _flag(
        "OEM_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "OEM Authorization",
        "OEM verification unavailable",
        "OEM verification unavailable",
    ),
    _flag(
        "PAN_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "PAN identity mismatch",
        "PAN identity mismatch",
    ),
    _flag(
        "PAN_INACTIVE",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "PAN inactive",
        "PAN inactive",
    ),
    _flag(
        "PAN_INVALID",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "PAN invalid",
        "PAN invalid",
    ),
    _flag(
        "PAN_NOT_FOUND",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "PAN not found",
        "PAN not found",
    ),
    _flag(
        "PAN_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "PAN / Income Tax",
        "PAN verification unavailable",
        "PAN verification unavailable",
    ),
    _flag(
        "PROCUREMENT_DEBARMENT_ACTIVE",
        FlagSeverity.HIGH,
        "Blacklisting / Debarment",
        "Active procurement debarment / restriction",
        "Active procurement debarment / restriction",
    ),
    _flag(
        "PROCUREMENT_ELIGIBILITY_UNVERIFIABLE",
        FlagSeverity.MEDIUM,
        "Blacklisting / Debarment",
        "Procurement eligibility unverifiable",
        "Procurement eligibility unverifiable",
    ),
    _flag(
        "RECOMMENDATION_AUTOMATIC_ACCEPT",
        FlagSeverity.INFO,
        "AI Recommendation",
        "Recommendation: automatic accept",
        "Recommendation: automatic accept",
    ),
    _flag(
        "RECOMMENDATION_AUTOMATIC_REJECT",
        FlagSeverity.CRITICAL,
        "AI Recommendation",
        "Recommendation: automatic reject",
        "Recommendation: automatic reject",
    ),
    _flag(
        "RECOMMENDATION_CONFIDENCE_LOW",
        FlagSeverity.LOW,
        "AI Recommendation",
        "Recommendation confidence low",
        "Recommendation confidence low",
    ),
    _flag(
        "RECOMMENDATION_ESCALATE_TO_REVIEW",
        FlagSeverity.MEDIUM,
        "AI Recommendation",
        "Recommendation: escalate to review",
        "Recommendation: escalate to review",
    ),
    _flag(
        "RECOMMENDATION_INCOMPLETE",
        FlagSeverity.LOW,
        "AI Recommendation",
        "Recommendation incomplete",
        "Recommendation incomplete",
    ),
    _flag(
        "REGISTRATION_CHANGE_UNEXPLAINED",
        FlagSeverity.HIGH,
        "Registration / Status Checks",
        "Registration change unexplained",
        "Registration change unexplained",
    ),
    _flag(
        "REGISTRATION_RECENTLY_CHANGED",
        FlagSeverity.MEDIUM,
        "Registration / Status Checks",
        "Registration recently changed",
        "Registration recently changed",
    ),
    _flag(
        "REGISTRATION_STALE_NOT_VERIFIED",
        FlagSeverity.MEDIUM,
        "Registration / Status Checks",
        "Registration stale/not verified",
        "Registration stale/not verified",
    ),
    _flag(
        "REGISTRATION_STATUS_INCONSISTENT",
        FlagSeverity.HIGH,
        "Registration / Status Checks",
        "Registration status inconsistent",
        "Registration status inconsistent",
    ),
    _flag(
        "REGISTRATION_VERIFICATION_INCOMPLETE",
        FlagSeverity.LOW,
        "Registration / Status Checks",
        "Registration verification incomplete",
        "Registration verification incomplete",
    ),
    _flag(
        "REQUIRED_EVIDENCE_MISSING",
        FlagSeverity.HIGH,
        "Missing / Completeness Checks",
        "Required evidence missing",
        "Required evidence missing",
    ),
    _flag(
        "REQUIRED_FIELD_MISSING",
        FlagSeverity.HIGH,
        "Missing / Completeness Checks",
        "Required field missing",
        "Required field missing",
    ),
    _flag(
        "RISK_ASSESSMENT_INCOMPLETE",
        FlagSeverity.LOW,
        "Compliance Score / Risk Level",
        "Risk assessment incomplete",
        "Risk assessment incomplete",
    ),
    _flag(
        "RISK_LEVEL_HIGH",
        FlagSeverity.HIGH,
        "Compliance Score / Risk Level",
        "Risk level high",
        "Risk level high",
    ),
    _flag(
        "RISK_TREND_DETERIORATING",
        FlagSeverity.MEDIUM,
        "Compliance Score / Risk Level",
        "Risk trend deteriorating",
        "Risk trend deteriorating",
    ),
    _flag(
        "SCORING_FORMULA_UNDEFINED",
        FlagSeverity.MEDIUM,
        "Compliance Score / Risk Level",
        "Scoring formula undefined",
        "Scoring formula undefined",
    ),
    _flag(
        "SOLVENCY_THRESHOLD_NOT_MET",
        FlagSeverity.HIGH,
        "Financial Capacity",
        "Solvency threshold not met",
        "Solvency threshold not met",
    ),
    _flag(
        "SOURCE_DOCUMENT_UNRECOVERABLE",
        FlagSeverity.HIGH,
        "Auditability / Evidence Traceability",
        "Source document unrecoverable",
        "Source document unrecoverable",
    ),
    _flag(
        "SOURCING_LOCATION_MISMATCH",
        FlagSeverity.MEDIUM,
        "Make in India / Local Content",
        "Sourcing location mismatch",
        "Sourcing location mismatch",
    ),
    _flag(
        "STARTUP_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "Startup India / DPIIT",
        "Startup identity mismatch",
        "Startup identity mismatch",
    ),
    _flag(
        "STARTUP_INELIGIBLE_FOR_EXEMPTION",
        FlagSeverity.HIGH,
        "Startup India / DPIIT",
        "Startup ineligible for exemption",
        "Startup ineligible for exemption",
    ),
    _flag(
        "STARTUP_RECOGNITION_EXPIRED",
        FlagSeverity.HIGH,
        "Startup India / DPIIT",
        "Startup recognition expired",
        "Startup recognition expired",
    ),
    _flag(
        "STARTUP_RECOGNITION_INVALID",
        FlagSeverity.HIGH,
        "Startup India / DPIIT",
        "Startup recognition invalid",
        "Startup recognition invalid",
    ),
    _flag(
        "STARTUP_RECOGNITION_NOT_FOUND",
        FlagSeverity.HIGH,
        "Startup India / DPIIT",
        "Startup recognition not found",
        "Startup recognition not found",
    ),
    _flag(
        "STARTUP_SECTOR_MISMATCH",
        FlagSeverity.MEDIUM,
        "Startup India / DPIIT",
        "Startup sector mismatch",
        "Startup sector mismatch",
    ),
    _flag(
        "STARTUP_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Startup India / DPIIT",
        "Startup verification unavailable",
        "Startup verification unavailable",
    ),
    _flag(
        "STATUTORY_REQUIREMENT_EXPIRED",
        FlagSeverity.HIGH,
        "Other Applicable Statutory Requirements",
        "Statutory requirement expired",
        "Statutory requirement expired",
    ),
    _flag(
        "STATUTORY_REQUIREMENT_INVALID",
        FlagSeverity.HIGH,
        "Other Applicable Statutory Requirements",
        "Statutory requirement invalid",
        "Statutory requirement invalid",
    ),
    _flag(
        "STATUTORY_REQUIREMENT_MISSING",
        FlagSeverity.HIGH,
        "Other Applicable Statutory Requirements",
        "Statutory requirement missing",
        "Statutory requirement missing",
    ),
    _flag(
        "STATUTORY_REQUIREMENT_SCOPE_MISMATCH",
        FlagSeverity.MEDIUM,
        "Other Applicable Statutory Requirements",
        "Statutory requirement scope mismatch",
        "Statutory requirement scope mismatch",
    ),
    _flag(
        "STATUTORY_REQUIREMENT_SUSPENDED_REVOKED",
        FlagSeverity.CRITICAL,
        "Other Applicable Statutory Requirements",
        "Statutory requirement suspended or revoked",
        "Statutory requirement suspended or revoked",
    ),
    _flag(
        "STATUTORY_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Other Applicable Statutory Requirements",
        "Statutory verification unavailable",
        "Statutory verification unavailable",
    ),
    _flag(
        "SUSPICIOUS_BIDDER_RELATIONSHIP_DETECTED",
        FlagSeverity.HIGH,
        "Cross-Bidder / Duplicate / Near-Duplicate Detection",
        "Suspicious bidder relationship detected",
        "Suspicious bidder relationship detected",
    ),
    _flag(
        "TAX_DATA_MISMATCH",
        FlagSeverity.HIGH,
        "PAN / Income Tax",
        "Tax data mismatch",
        "Tax data mismatch",
    ),
    _flag(
        "TENDER_APPLICABILITY_UNDEFINED",
        FlagSeverity.MEDIUM,
        "Tender Applicability / Exemption Checks",
        "Tender applicability undefined",
        "Tender applicability undefined",
    ),
    _flag(
        "TENDER_REQUIREMENT_COMPLIANCE_UNCLEAR",
        FlagSeverity.MEDIUM,
        "Other Tender-Specific Requirements",
        "Tender requirement compliance unclear",
        "Tender requirement compliance unclear",
    ),
    _flag(
        "TENDER_REQUIREMENT_EVIDENCE_INVALID",
        FlagSeverity.HIGH,
        "Other Tender-Specific Requirements",
        "Tender requirement evidence invalid",
        "Tender requirement evidence invalid",
    ),
    _flag(
        "TENDER_REQUIREMENT_EVIDENCE_MISSING",
        FlagSeverity.HIGH,
        "Other Tender-Specific Requirements",
        "Tender requirement evidence missing",
        "Tender requirement evidence missing",
    ),
    _flag(
        "TENDER_REQUIREMENT_THRESHOLD_NOT_MET",
        FlagSeverity.HIGH,
        "Other Tender-Specific Requirements",
        "Tender requirement threshold not met",
        "Tender requirement threshold not met",
    ),
    _flag(
        "TENDER_SPECIFIC_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Other Tender-Specific Requirements",
        "Tender-specific verification unavailable",
        "Tender-specific verification unavailable",
    ),
    _flag(
        "TURNOVER_BELOW_THRESHOLD",
        FlagSeverity.HIGH,
        "Financial Capacity",
        "Turnover below threshold",
        "Turnover below threshold",
    ),
    _flag(
        "UDYAM_CATEGORY_MISMATCH",
        FlagSeverity.HIGH,
        "Udyam / MSME",
        "Udyam category mismatch",
        "Udyam category mismatch",
    ),
    _flag(
        "UDYAM_IDENTITY_MISMATCH",
        FlagSeverity.HIGH,
        "Udyam / MSME",
        "Udyam identity mismatch",
        "Udyam identity mismatch",
    ),
    _flag(
        "UDYAM_INACTIVE",
        FlagSeverity.HIGH,
        "Udyam / MSME",
        "Udyam registration inactive",
        "Udyam registration inactive",
    ),
    _flag(
        "UDYAM_INVALID",
        FlagSeverity.HIGH,
        "Udyam / MSME",
        "Udyam number invalid",
        "Udyam number invalid",
    ),
    _flag(
        "UDYAM_NOT_FOUND",
        FlagSeverity.HIGH,
        "Udyam / MSME",
        "Udyam registration not found",
        "Udyam registration not found",
    ),
    _flag(
        "UDYAM_VERIFICATION_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Udyam / MSME",
        "Udyam verification unavailable",
        "Udyam verification unavailable",
    ),
    _flag(
        "UDYAM_SCOPE_MISMATCH",
        FlagSeverity.MEDIUM,
        "Udyam / MSME",
        "Udyam scope mismatch",
        "Udyam scope mismatch",
    ),
    _flag(
        "VERIFICATION_DATA_STALE",
        FlagSeverity.MEDIUM,
        "Verification Infrastructure Checks",
        "Verification data stale",
        "Verification data stale",
    ),
    _flag(
        "VERIFICATION_NON_REPRODUCIBLE",
        FlagSeverity.HIGH,
        "Auditability / Evidence Traceability",
        "Verification non-reproducible",
        "Verification non-reproducible",
    ),
    _flag(
        "VERIFICATION_PROVIDER_ERROR",
        FlagSeverity.MEDIUM,
        "Verification Infrastructure Checks",
        "Verification provider error",
        "Verification provider error",
    ),
    _flag(
        "VERIFICATION_PROVIDER_TIMEOUT",
        FlagSeverity.MEDIUM,
        "Verification Infrastructure Checks",
        "Verification provider timeout",
        "Verification provider timeout",
    ),
    _flag(
        "VERIFICATION_PROVIDER_UNAVAILABLE",
        FlagSeverity.MEDIUM,
        "Verification Infrastructure Checks",
        "Verification provider unavailable",
        "Verification provider unavailable",
    ),
)

FLAG_REGISTRY: dict[str, FlagDefinition] = {item.flag_id: item for item in _FLAGS}


def get_flag_definition(flag_id: str) -> FlagDefinition:
    """Return the static definition for ``flag_id``."""

    try:
        return FLAG_REGISTRY[flag_id]
    except KeyError as exc:
        raise UnknownFlagError(f"Unknown flag ID: {flag_id!r}") from exc
