"""Canonical financial flag ID constants.

These string constants mirror the canonical flag IDs registered in
:mod:`compliance_engine.flags.registry`. They are kept as literals here
only to avoid typos in the financial package; the registry remains the
single source of truth for flag metadata (severity, title, description).
"""

from __future__ import annotations

TURNOVER_BELOW_THRESHOLD = "TURNOVER_BELOW_THRESHOLD"
TURNOVER_PERIOD_MISMATCH = "TURNOVER_PERIOD_MISMATCH"
TURNOVER_DATA_MISSING = "TURNOVER_DATA_MISSING"
TURNOVER_TREND_ANOMALY = "TURNOVER_TREND_ANOMALY"

NET_WORTH_BELOW_THRESHOLD = "NET_WORTH_BELOW_THRESHOLD"
SOLVENCY_REQUIREMENT_FAILED = "SOLVENCY_REQUIREMENT_FAILED"

BALANCE_SHEET_INCOMPLETE = "BALANCE_SHEET_INCOMPLETE"
AUDIT_EVIDENCE_MISSING = "AUDIT_EVIDENCE_MISSING"

FINANCIAL_DATA_INCONSISTENCY = "FINANCIAL_DATA_INCONSISTENCY"
FINANCIAL_YEAR_MISMATCH = "FINANCIAL_YEAR_MISMATCH"
FINANCIAL_CAPACITY_MISSING = "FINANCIAL_CAPACITY_MISSING"


__all__ = [
    "AUDIT_EVIDENCE_MISSING",
    "BALANCE_SHEET_INCOMPLETE",
    "FINANCIAL_CAPACITY_MISSING",
    "FINANCIAL_DATA_INCONSISTENCY",
    "FINANCIAL_YEAR_MISMATCH",
    "NET_WORTH_BELOW_THRESHOLD",
    "SOLVENCY_REQUIREMENT_FAILED",
    "TURNOVER_BELOW_THRESHOLD",
    "TURNOVER_DATA_MISSING",
    "TURNOVER_PERIOD_MISMATCH",
    "TURNOVER_TREND_ANOMALY",
]